### ISSUE TITLE
Scaffolding broken for net45x projects

### ISSUE THREAD

**Issue by prafullbhosale** [aspnet/Scaffolding#338]
On a project that targets net45x run 

`dotnet aspnet-codegenerator -p . controller -name EmptyController` 

It fails with the error 

```
There was an error running the template C:\Users\prbhosal\.nuget\packages\microsoft.visualstudio.web.codegenerators.mvc\1.0.0-t003872216\Templates\ControllerGenerator\EmptyController.cshtml: Template Processing Failed:(8,12): error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
```

cc @vkichline

**Comment by prafullbhosale** [comment]
### Workaround
Add Reference to Microsoft.CSharp in the project. 
```xml
<Reference Include="Microsoft.CSharp" />
```

**Comment by prafullbhosale** [comment]
Fixed in: https://github.com/aspnet/Templates/pull/719
