### ISSUE TITLE
Scaffolding Controller with EF broken for projects targeting net4x

### ISSUE THREAD

**Issue by prafullbhosale** [aspnet/Scaffolding#339]
On a project targeting net4x run 
`dotnet aspnet-codegenerator -p . controller -name CarController -m WebApplication1.Models.Car -dc WebApplication1.Data.ApplicationDbContext`

It fails with error

```
'Could not load file or assembly 'WebApplication1.exe' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)'

```

cc @vkichline

**Comment by prafullbhosale** [comment]
Fixed in e28f8308da1d96faf6a089f820242eb0820ef4db
