### ISSUE TITLE
Upgrade CLI.Utils package to 4215

### ISSUE THREAD

**Issue by prafullbhosale** [aspnet/Scaffolding#350]
With the sdk changes, scaffolding fails with the below error: 

```
'Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DotNet.Cli.Utils.MSBuildProject.get_DepsJsonPath()
   at Microsoft.DotNet.Cli.Utils.ProjectDependenciesCommandResolver.ResolveFromProjectDependencies(String projectDirectory, NuGetFramework framework, String configuration, String commandName, IEnumerable`1 commandArguments, String outputPath, String buildBasePath)
   at Microsoft.DotNet.Cli.Utils.ProjectDependenciesCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
   at Microsoft.DotNet.Cli.Utils.ProjectDependenciesCommandFactory.FindProjectDependencyCommands(String commandName, IEnumerable`1 commandArgs, String configuration, NuGetFramework framework, String outputPath, String buildBasePath, String projectDirectory)
   at Microsoft.DotNet.Cli.Utils.ProjectDependenciesCommandFactory.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration)
   at Microsoft.VisualStudio.Web.CodeGeneration.Tools.Program.BuildAndDispatchDependencyCommand(String[] args, String projectPath, String buildBasePath, String configuration, Boolean noBuild, ILogger logger)
   at Microsoft.VisualStudio.Web.CodeGeneration.Tools.Program.<>c__DisplayClass9_0.<Execute>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.Tools.Program.Main(String[] args)'
```

To fix this, the `Microsoft.Dotnet.Cli.Utils` package needs to be updated to version `1.0.0-preview4-004215`

### Sample Project

```xml
<Project ToolsVersion="15.0" Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>

  <PropertyGroup>
    <PackageTargetFallback>$(PackageTargetFallback);portable-net45+win8+wp8+wpa81;</PackageTargetFallback>
  </PropertyGroup>

  <PropertyGroup>
    <UserSecretsId>aspnet-WebApplication1-521534d7-1e88-42a5-b269-92350a9f1b99</UserSecretsId>
  </PropertyGroup>

  <PropertyGroup>
    <GlobalExclude>$(GlobalExclude);bin\**;obj\**;node_modules\**;jspm_packages\**;bower_components\**;**\*.user;**\*.*proj</GlobalExclude>
  </PropertyGroup>

  <ItemGroup>
    <None Include="**\*" />
    <Compile Include="**\*.cs" />
    <EmbeddedResource Include="**\*.resx" />
    <Content Include="wwwroot\**" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="**\*.cshtml" Exclude="wwwroot\**\*.cshtml" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="**\*.config" Exclude="wwwroot\**\*.config" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="**\*.json" Exclude="wwwroot\**\*.json" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETCore.App" Version="1.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="1.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Routing" Version="1.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Server.IISIntegration" Version="1.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Server.Kestrel" Version="1.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="1.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink.Loader" Version="14.0.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Cookies" Version="1.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="1.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="1.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="1.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="1.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.Design" Version="1.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="1.0.0-msbuild2-final" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="1.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="1.0.0-msbuild2-final" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="1.0.0-msbuild2-final" />
    <DotNetCliToolReference Include="Microsoft.Extensions.SecretManager.Tools" Version="1.0.0-msbuild2-final" />
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.0-msbuild2-final" />
  </ItemGroup>


</Project>

```
### Repro steps
1. Run `dotnet restore` on the above project
2. In the project folder, run `dotnet aspnet-codegenerator -p <projectname>.csproj controller --controllerName EmptyController`

### Dotnet CLI info
```
.NET Command Line Tools (1.0.0-preview4-004215)

Product Information:
 Version:            1.0.0-preview4-004215
 Commit SHA-1 hash:  7a0d3e255a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10240
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\1.0.0-preview4-004215
```

**Comment by prafullbhosale** [comment]
cc @mlorbetske, @barrytang

**Comment by piotrpMSFT** [comment]
Ok, think I see what's going on.

The code that is throwing looks at MSBuild evaluation results to find the path to an output file. This means that MSBuild loads the csproj file, evaluates it, and gives back a property.

The MSBuild referenced by the older utils package is not aware of the SDK attribute. It therefore does not pull in the SDK and does not have access to the property. It gives back null to the CLI which then throws a null ref.

I expect that the tool continues to work for RC1 csproj's. It simply doesn't have the new <Project SDK=...> feature yet and is being executed against a csproj file it doesn't know how to reason about. We can either fix the tool to fail gracefully or update the CLI Utils so it doesn't fail.

If you see inconsistencies please let me know. This is based on looking at code for a few seconds, I have not seen a repro that I can debug.

**Comment by prafullbhosale** [comment]
https://github.com/aspnet/Scaffolding/commit/ffb59b0edce5c047c6ccd044c58a7510a0736350
