### ISSUE TITLE
[Flaky test]: Test failed on Ubuntu \ OSX with no code changes

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Scaffolding#459]
```
SimulationModeTests.TestControllerWithContext 
Scaffold command failed with exit code 134
Expected: True
Actual:   False
   at Microsoft.VisualStudio.Web.CodeGeneration.E2E_Test.E2ETestBase.Scaffold(String[] args, String testProjectPath)
   at Microsoft.VisualStudio.Web.CodeGeneration.E2E_Test.SimulationModeTests.TestControllerWithContext()
```

```
SimulationModeTests.TestControllerWithContext 
Scaffold command failed with exit code 134
Expected: True
Actual:   False
   at Microsoft.VisualStudio.Web.CodeGeneration.E2E_Test.E2ETestBase.Scaffold(String[] args, String testProjectPath)
   at Microsoft.VisualStudio.Web.CodeGeneration.E2E_Test.SimulationModeTests.TestControllerWithContext()
...
Installed:
      128 package(s) to /home/aspnetagent/buildAgent/temp/buildTmp/tmpfiles/28aeb633-1fdc-4f7c-937d-95c93074b6aa/Root/Test.csproj
Command Line: -p /home/aspnetagent/buildAgent/temp/buildTmp/tmpfiles/28aeb633-1fdc-4f7c-937d-95c93074b6aa/Root --simulation-mode controller --controllerName CarsController --relativeFolderPath SimControllers
Microsoft (R) Build Engine version 15.2.93.5465
Copyright (C) Microsoft Corporation. All rights reserved.
/home/aspnetagent/buildAgent/temp/buildTmp/tmpfiles/28aeb633-1fdc-4f7c-937d-95c93074b6aa/Root/obj/Test.csproj.nuget.g.targets(9,5): warning MSB4011: "/datadrive/2b0c8ce712895332/packages/microsoft.visualstudio.web.codegeneration.tools/2.0.0-preview1-24601/build/netstandard1.0/microsoft.visualstudio.web.codegeneration.tools.targets" cannot be imported again. It was already imported at "/home/aspnetagent/buildAgent/temp/buildTmp/tmpfiles/28aeb633-1fdc-4f7c-937d-95c93074b6aa/Root/obj/Test.csproj.codegeneration.targets (11,5)". This is most likely a build authoring error. This subsequent import will be ignored. [/home/aspnetagent/buildAgent/temp/buildTmp/tmpfiles/28aeb633-1fdc-4f7c-937d-95c93074b6aa/Root/Test.csproj]
/datadrive/2b0c8ce712895332/.dotnet/sdk/2.0.0-preview1-005825/Sdks/Microsoft.NET.Sdk/build/Microsoft.PackageDependencyResolution.targets(155,5): error : Unexpected dependency 'Microsoft.Extensions.Logging.Abstractions' with no version number. [/home/aspnetagent/buildAgent/temp/buildTmp/tmpfiles/28aeb633-1fdc-4f7c-937d-95c93074b6aa/Root/Test.csproj]
/datadrive/2b0c8ce712895332/.dotnet/sdk/2.0.0-preview1-005825/Sdks/Microsoft.NET.Sdk/build/Microsoft.PackageDependencyResolution.targets(155,5): error : Unexpected dependency 'Microsoft.Extensions.Logging.Abstractions' with no version number. [/home/aspnetagent/buildAgent/temp/buildTmp/tmpfiles/28aeb633-1fdc-4f7c-937d-95c93074b6aa/Root/Test.csproj]
/datadrive/2b0c8ce712895332/.dotnet/sdk/2.0.0-preview1-005825/Sdks/Microsoft.NET.Sdk/build/Microsoft.PackageDependencyResolution.targets(155,5): error : Unexpected dependency 'Microsoft.Extensions.Logging.Abstractions' with no version number. [/home/aspnetagent/buildAgent/temp/buildTmp/tmpfiles/28aeb633-1fdc-4f7c-937d-95c93074b6aa/Root/Test.csproj]
/datadrive/2b0c8ce712895332/.dotnet/sdk/2.0.0-preview1-005825/Sdks/Microsoft.NET.Sdk/build/Microsoft.PackageDependencyResolution.targets(155,5): error : Unexpected dependency 'Microsoft.Extensions.Logging.Abstractions' with no version number. [/home/aspnetagent/buildAgent/temp/buildTmp/tmpfiles/28aeb633-1fdc-4f7c-937d-95c93074b6aa/Root/Test.csproj]
```

## Repros
4/25/17: http://aspnetci/viewLog.html?buildId=208053&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR&tab=buildLog&filter=err

**Comment by pranavkm** [comment]
@prafullbhosale this seems to have been fixed, but could you have a look to ensure there isn't a cause for the flakiness?

**Comment by mikeharder** [comment]
This failed again today.  I started a list of repros in the main comment.

**Comment by prafullbhosale** [comment]
The failure seems to be related to a nuget package install on the test project. 

```
  ...
  Installing Microsoft.AspNetCore.Razor.Runtime 2.0.0-preview1-24626.
  Installing Microsoft.AspNetCore.Html.Abstractions 2.0.0-preview1-24626.
  Installing Microsoft.AspNetCore.Antiforgery 2.0.0-preview1-24626.
  Installing Newtonsoft.Json.Bson 1.0.1.
  Installing Microsoft.Extensions.DependencyInjection.Abstractions 1.0.0.
  Installing Microsoft.Extensions.Configuration.Abstractions 1.0.0.
  Installing Microsoft.Extensions.Options 1.0.0.
  Installing Microsoft.AspNetCore.Hosting.Server.Abstractions 1.0.0.
/datadrive/2b0c8ce712895332/.dotnet/sdk/2.0.0-preview1-005825/NuGet.targets(97,5): error : Unable to resolve 'Microsoft.Extensions.Logging.Abstractions (>= 2.0.0-preview1-24626)' for '.NETCoreApp,Version=v2.0'. [/home/aspnetagent/buildAgent/temp/buildTmp/tmpfiles/01eb8d99-253b-49e7-ac6a-ee831b0d91d3/Root/Test.csproj]
```

I have seen this before on a few occasions, when a new set of packages is being uploaded to myget but isn't fully done. 

I remember @pranavkm made the builds so that the Tools repos are built at the end, doesn't look like that is enough though. 

For the universe builds, is it possible to create a local feed with all packages from the current build available?

**Comment by pranavkm** [comment]
> I remember @pranavkm made the builds so that the Tools repos are built at the end, doesn't look like that is enough though. 

That was specifically in the patch branch. We build things as usual in regular builds. More importantly, we don't change the feeds as part of the build. One possible solution would be to use the `NUGET_PACKAGES` directory as the source (if it's available) although it's not intuitively obvious why it works.

**Comment by mikeharder** [comment]
This sounds like a dup of the general issue where our MyGet feed cannot be relied on to always restore correctly.  We have a plan to fix this all-up by implementing a proxy which selects the latest working MyGet feed.

https://github.com/aspnet/aspnetci-nugetsyncbuddy/issues/1

**Comment by mikeharder** [comment]
New plan to fix this issue by pinning versions: https://github.com/aspnet/KoreBuild/issues/239

**Comment by mikeharder** [comment]
Keeping issue open to track test flakiness until aspnet/KoreBuild#239 is fixed.

**Comment by mikeharder** [comment]
@ryanbrandenburg: Please close if the test has been relatively stable lately.

**Comment by ryanbrandenburg** [comment]
This seems to have been fine lately, we can re-open if it re-surges.
