### ISSUE TITLE
[Flaky test]: ScaffolderTests.TestAreaGenerator

### ISSUE THREAD

**Issue by halter73** [aspnet/Scaffolding#479]
```
AreaScaffolderTests.TestAreaGenerator 

Assert.True() Failure
Expected: True
Actual:   False
   at Microsoft.VisualStudio.Web.CodeGeneration.E2E_Test.E2ETestBase.VerifyFileAndContent(String generatedFilePath, String baselineFile)
   at Microsoft.VisualStudio.Web.CodeGeneration.E2E_Test.AreaScaffolderTests.TestAreaGenerator()
```

Example failure: http://aspnetci/viewLog.html?buildId=217356&tab=buildResultsDiv&buildTypeId=Lite_UniverseTest#testNameId1186750468449124074

All failures: http://aspnetci/project.html?projectId=XPlat&buildTypeId=&tab=testDetails&testNameId=1186750468449124074&order=TEST_STATUS_DESC&branch_XPlat=__all_branches__&itemsCount=50

**Comment by halter73** [comment]
After looking at the stack traces for all the failures in http://aspnetci/viewLog.html?buildId=217356&tab=buildResultsDiv&buildTypeId=Lite_UniverseTest I'm starting to think their all the same issue.

For the other tests that I looked at, they never passed on the tc agents. E.g. http://aspnetci/project.html?branch_XPlat=__all_branches__&buildTypeId=&tab=testDetails&projectId=XPlat&testNameId=6404928015061455304&itemsCount=50&order=TEST_STATUS_DESC&page=1
