### ISSUE TITLE
Microsoft.CodeAnalysis.CSharp 2.1.0 package breaks scaffolding

### ISSUE THREAD

**Issue by gpshonik** [aspnet/Scaffolding#501]
## Minimal Repro

File...New Project...Web...ASP.NET Core Web Application

Add nuget package  [Microsoft.CodeAnalysis.CSharp](https://www.nuget.org/packages/Microsoft.CodeAnalysis.CSharp/)  (adding this package to enable C# 7 language features in Razor Views)

Right Click Controllers...Add Controller...'MVC Controller - Empty'

![image](https://cloud.githubusercontent.com/assets/1524361/26408059/688c9620-4062-11e7-8009-581d6d7b73d7.png)

Click Add

This executes the following command:

```cmd
C:\Program Files\dotnet\dotnet.exe aspnet-codegenerator --project "C:\Work\Temp\ScaffoldingTest\ScaffoldingTest\ScaffoldingTest.csproj" --no-build controller --force --controllerName DefaultController --relativeFolderPath Controllers --noViews
```

which results in the following exception:

```txt
There was an error running the selected code generator:

'Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at System.Composition.Hosting.ContainerConfiguration.<WithAssemblies>b__0(Assembly a)
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at Microsoft.CodeAnalysis.Host.Mef.MefHostServices.Create(IEnumerable`1 assemblies)
   at Microsoft.CodeAnalysis.Host.Mef.MefHostServices.get_DefaultHost()
   at Microsoft.VisualStudio.Web.CodeGeneration.Utils.RoslynWorkspace..ctor(IProjectContext projectInformation, String configuration)
   at Microsoft.VisualStudio.Web.CodeGeneration.Design.CodeGenCommandExecutor.AddFrameworkServices(ServiceProvider serviceProvider, IProjectContext projectInformation)
   at Microsoft.VisualStudio.Web.CodeGeneration.Design.CodeGenCommandExecutor.Execute()
   at Microsoft.VisualStudio.Web.CodeGeneration.Design.Program.<>c__DisplayClass5_0.<<Execute>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass79_0.<OnExecute>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.Design.Program.Execute(String[] args, ConsoleLogger logger)
   at Microsoft.VisualStudio.Web.CodeGeneration.Design.Program.Main(String[] args)'
```

**Other scaffolding operations (such as scaffolding a view for an action)  also throw the same exception.**

## .csproj

```xml

<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <PackageTargetFallback>$(PackageTargetFallback);portable-net45+win8+wp8+wpa81;</PackageTargetFallback>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.0.0" />
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.2" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.2" />
    <PackageReference Include="Microsoft.VisualStudio.Web.BrowserLink" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.Session" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.2" />
    <PackageReference Include="System.ServiceModel.Http" Version="4.3.0" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="4.3.0" />
    <PackageReference Include="System.ServiceModel.Security" Version="4.3.0" />
    <PackageReference Include="System.Xml.XmlSerializer" Version="4.3.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="2.1.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="2.1.0" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="1.0.1" />
  </ItemGroup>

</Project>
```

Removing the following packages restores proper scaffolding functionality
```xml
 <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="2.1.0" />
 <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="2.1.0" />
```

**Comment by prafullbhosale** [comment]
@gpshonik The scaffolding package `<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="1.1.1" />` is built using Roslyn packages version 1.3.0 which is why when you add a reference to 2.1.0 version packages, there are 
errors while running scaffolding.

**Comment by prafullbhosale** [comment]
@gpshonik can you try adding the below package to your project and see if that helps? 

```xml
<PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="2.1.0" />
```

**Comment by gpshonik** [comment]
@prafullbhosale Sorry for the delay.  I can confirm that adding ```Microsoft.CodeAnalysis.CSharp.Workspaces``` package (either ```2.1.0``` or ```2.2.0```) allows the scaffolding command to complete successfully! Thank you!

**Comment by prafullbhosale** [comment]
Closing this now! Thanks for reporting this.
