### ISSUE TITLE
Could not get the reflection type for DbContext

### ISSUE THREAD

**Issue by feco93** [aspnet/Scaffolding#682]
I have followed the instructions from this tutorial:
https://docs.microsoft.com/en-us/aspnet/core/tutorials/razor-pages/model

Unfortunately I have faced with this problem:
Could not get the reflection type for DbContext : RazorPageSample.MovieDbContext
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)

I have installed Microsoft.CodeAnalysis.CSharp.Workspaces 2.6.1 (https://github.com/aspnet/Scaffolding/issues/430), but it didn't help.

Versions:
Microsoft.VisualStudio.Web.CodeGeneration.Tools 2.0.0
dotnet 2.0.2

**Comment by feco93** [comment]
After running the project the problem has solved. What was the problem?

**Comment by annerajb** [comment]
I still have this issue what do you mean that running the project solved?
Did you just load the website and scaffolding magically worked?

**Comment by feco93** [comment]
Running the sample project. I think the problem was that i didn't build the project... So i close it.
