### ISSUE TITLE
Scaffolding hangs on CI

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Scaffolding#697]
We're running into a problem on the CI where the tests will hang (and then usually fail) after running the a CodeGenerator.

A non-exhaustive list of instances of this can be found [here](http://aspnetci/viewLog.html?buildId=413372&buildTypeId=XPlat_Windows_Win8_Universe).

Example:
```
[Test Output]
Restoring packages for /Users/asplab/TeamCity/temp/buildTmp/tmpfiles/cd9f6128-43b2-4987-8951-2043c30f0a34/Root/Test.csproj...
  Restoring packages for /Users/asplab/TeamCity/temp/buildTmp/tmpfiles/cd9f6128-43b2-4987-8951-2043c30f0a34/Library1/Library1.csproj...
  Generating MSBuild file /Users/asplab/TeamCity/temp/buildTmp/tmpfiles/cd9f6128-43b2-4987-8951-2043c30f0a34/Library1/obj/Library1.csproj.nuget.g.props.
  Generating MSBuild file /Users/asplab/TeamCity/temp/buildTmp/tmpfiles/cd9f6128-43b2-4987-8951-2043c30f0a34/Library1/obj/Library1.csproj.nuget.g.targets.
  Restore completed in 570.03 ms for /Users/asplab/TeamCity/temp/buildTmp/tmpfiles/cd9f6128-43b2-4987-8951-2043c30f0a34/Library1/Library1.csproj.
  Generating MSBuild file /Users/asplab/TeamCity/temp/buildTmp/tmpfiles/cd9f6128-43b2-4987-8951-2043c30f0a34/Root/obj/Test.csproj.nuget.g.props.
  Generating MSBuild file /Users/asplab/TeamCity/temp/buildTmp/tmpfiles/cd9f6128-43b2-4987-8951-2043c30f0a34/Root/obj/Test.csproj.nuget.g.targets.
  Restore completed in 2.67 sec for /Users/asplab/TeamCity/temp/buildTmp/tmpfiles/cd9f6128-43b2-4987-8951-2043c30f0a34/Root/Test.csproj.
Microsoft (R) Build Engine version 15.6.82.30579 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 105.68 ms for /Users/asplab/TeamCity/temp/buildTmp/tmpfiles/cd9f6128-43b2-4987-8951-2043c30f0a34/Library1/Library1.csproj.
  Restore completed in 126.93 ms for /Users/asplab/TeamCity/temp/buildTmp/tmpfiles/cd9f6128-43b2-4987-8951-2043c30f0a34/Root/Test.csproj.
  Library1 -> /Users/asplab/TeamCity/temp/buildTmp/tmpfiles/cd9f6128-43b2-4987-8951-2043c30f0a34/Library1/bin/Release/netstandard2.0/Library1.dll
/Users/asplab/TeamCity/work/33bdfc1cae7b2a38/.dotnet/sdk/2.1.300-preview2-008251/Microsoft.Common.CurrentVersion.targets(2052,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "xyz.dll". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [/Users/asplab/TeamCity/temp/buildTmp/tmpfiles/cd9f6128-43b2-4987-8951-2043c30f0a34/Root/Test.csproj]
  Test -> /Users/asplab/TeamCity/temp/buildTmp/tmpfiles/cd9f6128-43b2-4987-8951-2043c30f0a34/Root/bin/Release/netcoreapp2.0/Test.dll

Build succeeded.

/Users/asplab/TeamCity/work/33bdfc1cae7b2a38/.dotnet/sdk/2.1.300-preview2-008251/Microsoft.Common.CurrentVersion.targets(2052,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "xyz.dll". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [/Users/asplab/TeamCity/temp/buildTmp/tmpfiles/cd9f6128-43b2-4987-8951-2043c30f0a34/Root/Test.csproj]
    1 Warning(s)
    0 Error(s)

Time Elapsed 00:00:07.54
Information:: Finding the generator 'area'...
Information:: Running the generator 'area'...
Checking if file is generated at /Users/asplab/TeamCity/temp/buildTmp/tmpfiles/cd9f6128-43b2-4987-8951-2043c30f0a34/Root/ScaffoldingReadMe.txt
[18:41:12]	Assert.True() Failure
Expected: True
Actual:   False
[18:41:12]	   at Microsoft.VisualStudio.Web.CodeGeneration.E2E_Test.E2ETestBase.VerifyFileAndContent(String generatedFilePath, String baselineFile) in /_/test/E2E_Test/E2ETestBase.cs:line 50
   at Microsoft.VisualStudio.Web.CodeGeneration.E2E_Test.AreaScaffolderTests.TestAreaGenerator() in /_/test/E2E_Test/AreaScaffolderTests.cs:line 48
```

**Comment by ryanbrandenburg** [comment]
CC @prafullbhosale who sounded like he was already working on this.

**Comment by prafullbhosale** [comment]
@ryanbrandenburg is this ok to close now? Or are you still seeing this?

**Comment by ryanbrandenburg** [comment]
I have not seen this in a bit, we can close it for now and re-open if we see it again.
