### ISSUE TITLE
Scaffolding in 2.1 fails with NullReferenceException

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Scaffolding#793]
![image](https://user-images.githubusercontent.com/2696087/40133377-644f89cc-58f4-11e8-8804-4188bb9c609a.png)

Repro:
1. File -> New -> ASP.NET Core Web Application -> MVC (No auth)
2. Solution explorer -> (right click) Add -> New Scaffolded Item...
3. -> Navigate to identity template and add Data context class:
![image](https://user-images.githubusercontent.com/2696087/40133427-947fb2ca-58f4-11e8-8675-5814169fbbd5.png)

Using 
```xml
<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.1.0-rtm-30752" />
```
VS 15.8 Preview2

**Comment by natemcmaster** [comment]
```
[Trace]: Command Line: --project C:\Users\namc\source\repos\WebApplication7\WebApplication7\WebApplication7.csproj --no-build --port-number 56176 controller --force --controllerName DefaultController --readWriteActions --restWithNoViews --dispatcher-version 2.0.0 --no-dispatch --simulation-mode
Scaffolding failed.
The type initializer for 'Microsoft.CodeAnalysis.CSharp.CSharpCompilationFactoryService' threw an exception.
[Trace]:    at Microsoft.CodeAnalysis.CSharp.CSharpCompilationFactoryService.Microsoft.CodeAnalysis.Host.ICompilationFactoryService.GetDefaultCompilationOptions() in /_/src/Workspaces/CSharp/Portable/LanguageServices/CSharpCompilationFactoryService.cs:line 45
   at Microsoft.CodeAnalysis.ProjectState.FixProjectInfo(ProjectInfo projectInfo) in /_/src/Workspaces/Core/Portable/Workspace/Solution/ProjectState.cs:line 127
   at Microsoft.CodeAnalysis.ProjectState..ctor(ProjectInfo projectInfo, HostLanguageServices languageServices, SolutionServices solutionServices) in /_/src/Workspaces/Core/Portable/Workspace/Solution/ProjectState.cs:line 82
   at Microsoft.CodeAnalysis.SolutionState.AddProject(ProjectInfo projectInfo) in /_/src/Workspaces/Core/Portable/Workspace/Solution/SolutionState.cs:line 468
   at Microsoft.CodeAnalysis.Solution.AddProject(ProjectInfo projectInfo) in /_/src/Workspaces/Core/Portable/Workspace/Solution/Solution.cs:line 244
   at Microsoft.CodeAnalysis.Workspace.OnProjectAdded_NoLock(ProjectInfo projectInfo, Boolean silent) in /_/src/Workspaces/Core/Portable/Workspace/Workspace.cs:line 398
   at Microsoft.CodeAnalysis.Workspace.OnProjectAdded(ProjectInfo projectInfo, Boolean silent) in /_/src/Workspaces/Core/Portable/Workspace/Workspace.cs:line 388
   at Microsoft.VisualStudio.Web.CodeGeneration.Utils.RoslynWorkspace.AddProject(IProjectContext context, String configuration)
   at Microsoft.VisualStudio.Web.CodeGeneration.Utils.RoslynWorkspace..ctor(IProjectContext projectInformation, String configuration)
   at Microsoft.VisualStudio.Web.CodeGeneration.Design.CodeGenCommandExecutor.AddFrameworkServices(ServiceProvider serviceProvider, IProjectContext projectInformation)
   at Microsoft.VisualStudio.Web.CodeGeneration.Design.CodeGenCommandExecutor.Execute(Action`1 simModeAction)
   at Microsoft.VisualStudio.Web.CodeGeneration.Design.Program.<>c__DisplayClass4_0.<<Execute>b__0>d.MoveNext()
```
cc @vijayrkn @prafullbhosale

**Comment by seancpeters** [comment]
@natemcmaster  @vijayrkn - I am unable to reproduce this locally. I'm using VS 15.8 Preview2 [27708.3001.d15.8stg]
and the same SDK you're using.

Regarding the Microsoft.VisualStudio.Web.CodeGeneration.Design package version (the above mentions using 2.1.0-rtm-30752):
- If I don't explicitly add this ref to the .csproj file, scaffolding adds 2.1.0-rtm-30762
- If I do add the package with version 2.1.0-rtm-30752, nuget resolves 2.1.0-rtm-30754

One thought: Is nuget still restoring when scaffolding is attempted?

**Comment by natemcmaster** [comment]
Are you restoring with https://dotnet.myget.org/F/dotnet-core/api/v3/index.json?

**Comment by seancpeters** [comment]
I was not using that source, but I've added it, and now the version you specified restores correctly. But the issue still does not reproduce for me. 

Btw: I'm getting the version of AspNetCore.App 2.1.0-rtm-30762 - let me know if you're getting a different version.

**Comment by natemcmaster** [comment]
I've attached my repro project: 
[WebApplication7.zip](https://github.com/aspnet/Scaffolding/files/2011088/WebApplication7.zip)

If it doesn't repro, maybe it's the result of upgrading to Roslyn 2.8.0. I'm running against aspnet 2.1.0-rtm-30752, which still has Roslyn 2.8.0-beta1 in it

**Comment by natemcmaster** [comment]
I think that must have been it. I upgraded my repro to our latest 2.1.0 candidate builds, and scaffolding runs fine.
